services:
  lazylang:
    build: .
    image: lazylang
    container_name: lazylang
    env_file:
      - .env
    environment:
      - PULSE_SERVER=/run/user/1000/pulse/native
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    group_add:
      - audio  

  libretranslate:
    image: libretranslate/libretranslate:latest
    environment:
      - LT_LOAD_ONLY=de,en
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/languages"]
      interval: 10s
      timeout: 5s
      retries: 10
